# Mod Properties
mod_id=cofh_core
mod_name=CoFH Core
mod_version=11.0.2

# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Platform Properties
java_version=25
mc_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.109

# Dependency Properties
jei_version=29.40.0.101
curios_version=15.0.0+26.1.2

# Publishing Properties

# Options: alpha, beta, release
release_type=release
