# Mod Properties
mod_id=cofh_core
mod_name=CoFH Core
mod_version=11.0.2

# Gradle Properties
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# Platform Properties
java_version=21
mc_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251

# Dependency Properties
jei_version=19.57.0.446
curios_version=9.5.1+1.21.1

# Publishing Properties

# Options: alpha, beta, release
release_type=release
